name: quran_app
description: "A Flutter project for a Quran app."

# Specify the version and build number for your application.
version: 1.0.0+1

# Define the Flutter SDK version.
environment:
  sdk:  '>=3.2.0 <4.0.0'

# Specify the dependencies for your project.
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.0  # Update to the latest version
  flutter_svg: ^1.1.6  # Update to the latest version
  dio: ^4.0.6

  cupertino_icons: ^1.0.2  # Update to the latest version

# Define development dependencies.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter-specific configurations.
flutter:
  uses-material-design: true

  # Specify assets for your application.
  assets:
    - assets/datas/
    - assets/svgs/

  # Specify custom fonts for your application.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
